'use strict';
const fs = require('fs');
const config = require('./config');
let body = `/**\n * {box direction dimension}\n * Generated by position.js\n */\n`;
config.BOX.forEach(box => {
  if (box === 'content') return;
  let BOX = box.slice(0, 3).toUpperCase();
  config.DIRECTION.forEach(dir =>{
    let DIR = dir.slice(0, 1).toUpperCase();
     body += `${BOX}-${DIR}(BoxDimension...)\n`;
     body += `  _BOX-DIR-DIM('${box}', '${dir}', BoxDimension)\n`;
   })
});
fs.writeFileSync(__dirname + '/_box.styl', body);
