'use strict';
const fs = require('fs');

const config = require('./config');

let body = `/**\n * {...POSITION-.DIRECTION}\n * Generated by position.js\n */\n`;
config.POSITION.forEach(pos => {
  const POS = pos.slice(0, 3).toUpperCase();
  body += `${POS}(args...)\n  _POS(${pos}, (${config.DIRECTION.join(' ')}), args)\n`;
  config.DIRECTION.forEach(dir => {
    const DIR = dir.slice(0, 1).toUpperCase();
    let ordering;
    switch (dir) {
      case 'top':
        ordering = 'top right left bottom';
        break;
      case 'right':
        ordering = 'right top bottom left';
        break;
      case 'bottom':
        ordering = 'bottom right left top';
        break;
      case 'left':
        ordering = 'left top bottom right';
        break;
      default:
        return;
    }
    body += `${POS}-${DIR}(args...)\n  _POS(\'${pos}\', (${ordering}), args)\n`;
   });
});
body += `\n`;
fs.writeFileSync(__dirname + '/_position.styl', body);
